#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

contains_fixed_text() {
  local needle="$1"
  local path="$2"
  if command -v rg >/dev/null 2>&1; then
    rg --fixed-strings --quiet -- "$needle" "$path"
  elif [[ -d "$path" ]]; then
    grep -RFq -- "$needle" "$path"
  else
    grep -Fq -- "$needle" "$path"
  fi
}

require_file() {
  local path="$1"
  if [[ ! -f "$path" ]]; then
    echo "Missing required native contract file: $path" >&2
    exit 1
  fi
}

require_directory() {
  local path="$1"
  if [[ ! -d "$path" ]]; then
    echo "Missing required native contract directory: $path" >&2
    exit 1
  fi
}

require_text() {
  local needle="$1"
  local path="$2"
  if ! contains_fixed_text "$needle" "$path"; then
    echo "Native contract is missing '$needle' in $path" >&2
    exit 1
  fi
}

forbid_text() {
  local needle="$1"
  local path="$2"
  if contains_fixed_text "$needle" "$path"; then
    echo "Native contract must not contain '$needle' in $path" >&2
    exit 1
  fi
}

require_after() {
  local completed_marker="$1"
  local deferred_action="$2"
  local path="$3"
  local completed_line
  local deferred_line
  completed_line="$(awk -v needle="$completed_marker" 'index($0, needle) { print NR; exit }' "$path")"
  deferred_line="$(awk -v needle="$deferred_action" 'index($0, needle) { print NR; exit }' "$path")"
  if [[ -z "$completed_line" || -z "$deferred_line" || "$deferred_line" -le "$completed_line" ]]; then
    echo "Native recovery action '$deferred_action' must occur after '$completed_marker' in $path" >&2
    exit 1
  fi
}

require_before() {
  local guard_marker="$1"
  local protected_action="$2"
  local path="$3"
  local guard_line
  local action_line
  guard_line="$(awk -v needle="$guard_marker" 'index($0, needle) { print NR; exit }' "$path")"
  action_line="$(awk -v needle="$protected_action" 'index($0, needle) { print NR; exit }' "$path")"
  if [[ -z "$guard_line" || -z "$action_line" || "$guard_line" -ge "$action_line" ]]; then
    echo "Safety guard '$guard_marker' must precede '$protected_action' in $path" >&2
    exit 1
  fi
}

require_file "$repo_root/shared-core/Cargo.toml"
require_file "$repo_root/shared-core/tests/two_device_sync.rs"
require_file "$repo_root/shared-core/include/dayflow_core.h"
require_file "$repo_root/shared-core/include/module.modulemap"
require_file "$repo_root/clients/generated/swift/DayflowCore.swift"
require_file "$repo_root/clients/generated/swift/DayflowCoreFFI.h"
require_file "$repo_root/clients/generated/swift/DayflowCoreFFI.modulemap"
require_file "$repo_root/clients/generated/kotlin/app/dayflow/core/dayflow_core.kt"
require_file "$repo_root/clients/ios/Sources/DayflowCoreBindings/DayflowCore.swift"
require_file "$repo_root/clients/ios/Package.swift"
require_file "$repo_root/clients/ios/DayflowMobile.xcodeproj/project.pbxproj"
require_file "$repo_root/clients/ios/DayflowMobile.xcodeproj/xcshareddata/xcschemes/DayflowMobileApp.xcscheme"
require_file "$repo_root/clients/ios/DayflowMobileApp/DayflowMobileAppEntry.swift"
require_file "$repo_root/clients/ios/DayflowMobileApp/DayflowMobileApp.entitlements"
require_file "$repo_root/clients/ios/Sources/DayflowMobile/DayflowMobilePushNotifications.swift"
require_file "$repo_root/clients/ios/Sources/DayflowMobile/DayflowMobilePushWakeContract.swift"
require_file "$repo_root/clients/android/app/build.gradle.kts"
require_file "$repo_root/clients/android/app/src/main/AndroidManifest.xml"
require_file "$repo_root/clients/android/app/src/test/java/app/dayflow/android/ChromeOsCapabilitiesTest.kt"
require_file "$repo_root/clients/android/app/src/main/java/app/dayflow/android/DayflowSyncWakeReceiver.kt"
require_file "$repo_root/clients/android/app/src/main/res/xml/network_security_config.xml"
require_file "$repo_root/scripts/build_dayflow_core_android.sh"
require_file "$repo_root/scripts/generate_dayflow_core_bindings.sh"
require_file "$repo_root/scripts/verify_dayflow_real_database_migration.sh"
require_text 'verify_dayflow_setup.sh' "$repo_root/scripts/verify_dayflow_real_database_migration.sh"
require_text 'verify_dayflow_setup.sh' "$repo_root/scripts/build_dayflow_core_xcframework.sh"
require_text 'verify_dayflow_setup.sh' "$repo_root/scripts/build_dayflow_core_ios_xcframework.sh"
require_text 'verify_dayflow_setup.sh' "$repo_root/scripts/release_dmg.sh"
require_text 'verify_dayflow_setup.sh' "$repo_root/scripts/release.sh"
require_before 'verify_dayflow_setup.sh' 'xcodebuild' "$repo_root/scripts/verify_dayflow_real_database_migration.sh"
require_before 'verify_dayflow_setup.sh' 'xcodebuild' "$repo_root/scripts/build_dayflow_core_xcframework.sh"
require_before 'verify_dayflow_setup.sh' 'xcodebuild' "$repo_root/scripts/build_dayflow_core_ios_xcframework.sh"
require_before 'verify_dayflow_setup.sh' 'xcodebuild' "$repo_root/scripts/release_dmg.sh"
require_before 'verify_dayflow_setup.sh' 'git add' "$repo_root/scripts/release.sh"
if command -v rg >/dev/null 2>&1; then
  workflow_preflight_count="$(rg -F 'run: bash scripts/verify_dayflow_setup.sh' "$repo_root/.github/workflows/dayflow-native-clients.yml" | wc -l | tr -d ' ')"
else
  workflow_preflight_count="$(grep -F -c 'run: bash scripts/verify_dayflow_setup.sh' "$repo_root/.github/workflows/dayflow-native-clients.yml" || true)"
fi
if [[ "$workflow_preflight_count" != "2" ]]; then
  echo "Native workflow must run the safe setup preflight in both Apple jobs (found ${workflow_preflight_count})." >&2
  exit 1
fi
require_file "$repo_root/clients/windows/Dayflow.Windows/Dayflow.Windows.csproj"
require_file "$repo_root/clients/windows/Dayflow.Windows/Package.appxmanifest"
require_file "$repo_root/clients/windows/Dayflow.Windows/Properties/PublishProfiles/win10-x64.pubxml"
require_file "$repo_root/clients/windows/Dayflow.Windows/Properties/PublishProfiles/win10-x86.pubxml"
require_file "$repo_root/clients/windows/Dayflow.Windows/Properties/PublishProfiles/win10-ARM64.pubxml"
require_file "$repo_root/clients/windows/Dayflow.Windows.Tests/Dayflow.Windows.Tests.csproj"
require_text 'runFullTrust' "$repo_root/clients/windows/Dayflow.Windows/Package.appxmanifest"
require_file "$repo_root/clients/windows/Dayflow.Windows.Tests/DayflowCoreInteropTests.cs"
require_file "$repo_root/clients/windows/Dayflow.Windows/Core/DayflowWindowsPushNotifications.cs"
require_file "$repo_root/clients/windows/Dayflow.Windows/Core/DayflowWindowsCapturePolicy.cs"
require_file "$repo_root/.github/workflows/dayflow-native-clients.yml"
require_file "$repo_root/Dayflow/Dayflow.xcodeproj/project.pbxproj"
require_file "$repo_root/Dayflow/Dayflow.xcodeproj/xcshareddata/xcschemes/Dayflow.xcscheme"

if ! cmp -s \
  "$repo_root/clients/generated/swift/DayflowCore.swift" \
  "$repo_root/clients/ios/Sources/DayflowCoreBindings/DayflowCore.swift"; then
  echo "The checked-in iOS UniFFI binding differs from clients/generated/swift/DayflowCore.swift." >&2
  echo "Run scripts/generate_dayflow_core_bindings.sh and copy the generated Swift binding." >&2
  exit 1
fi

require_text 'crate-type = ["rlib", "cdylib", "staticlib"]' "$repo_root/shared-core/Cargo.toml"
require_text '--features uniffi --target' "$repo_root/scripts/build_dayflow_core_xcframework.sh"
require_text 'module DayflowCoreFFI' "$repo_root/shared-core/include/module.modulemap"
require_text 'header "dayflow_core.h"' "$repo_root/shared-core/include/module.modulemap"
require_text 'dayflow_core_capture_decision_json' "$repo_root/shared-core/include/dayflow_core.h"
require_text 'dayflow_core_seal_key_version_json' "$repo_root/shared-core/include/dayflow_core.h"
require_text 'dayflow_core_project_keyring_json' "$repo_root/shared-core/include/dayflow_core.h"
require_text 'dayflow_core_sign_request_json' "$repo_root/shared-core/include/dayflow_core.h"
require_text 'dayflow_core_canonical_device_request_json' "$repo_root/shared-core/include/dayflow_core.h"
require_text 'requiredDayflowCoreSymbols' "$repo_root/clients/android/app/build.gradle.kts"
require_text 'uniffi_dayflow_core_fn_func_canonical_device_request' "$repo_root/clients/android/app/build.gradle.kts"
require_text 'dayflow_core_restore_recovery_keyring_json' "$repo_root/shared-core/include/dayflow_core.h"
require_text 'dayflow_core_rekey_envelopes_json' "$repo_root/shared-core/include/dayflow_core.h"
require_text 'dayflow_core_logical_day_key' "$repo_root/shared-core/include/dayflow_core.h"
require_text 'dayflow_core_free_string' "$repo_root/shared-core/include/dayflow_core.h"
require_text 'mktemp -d' "$repo_root/scripts/verify_dayflow_real_database_migration.sh"
require_text 'trap cleanup EXIT' "$repo_root/scripts/verify_dayflow_real_database_migration.sh"
require_text 'rekeyEnvelopesJson' "$repo_root/clients/generated/swift/DayflowCore.swift"
require_text 'rekeyEnvelopesJson' "$repo_root/clients/generated/kotlin/app/dayflow/core/dayflow_core.kt"
require_text 'canonicalDeviceRequest' "$repo_root/clients/generated/swift/DayflowCore.swift"
require_text 'canonicalDeviceRequest' "$repo_root/clients/generated/kotlin/app/dayflow/core/dayflow_core.kt"
require_text 'pub source: String' "$repo_root/shared-core/src/events.rs"
require_text 'pub derivation_mode: String' "$repo_root/shared-core/src/events.rs"
require_text 'shared_setting_contract_rejects_unknown_and_malformed_values' "$repo_root/shared-core/src/events.rs"
require_text 'c_abi_rejects_secret_shared_setting_before_sealing' "$repo_root/shared-core/src/ffi.rs"
require_text '#[serde(deny_unknown_fields)]' "$repo_root/shared-core/src/events.rs"
require_text 'capture_payload_rejects_unknown_media_fields_before_sealing' "$repo_root/shared-core/src/events.rs"
require_text 'two_devices_replay_offline_edits_through_an_opaque_relay' "$repo_root/shared-core/tests/two_device_sync.rs"
require_text 'relay_rejects_a_conflicting_immutable_event_without_partial_push' "$repo_root/shared-core/tests/two_device_sync.rs"
require_text 'replayed capture should be available to local chat' "$repo_root/shared-core/src/projection.rs"
require_text 'ConflictingKeyVersion' "$repo_root/shared-core/src/lib.rs"
require_text 'key_ring_rejects_a_different_key_for_an_existing_version' "$repo_root/shared-core/src/crypto.rs"
require_text 'testRustProjectionReplaysIntoACopiedMacReadModel' "$repo_root/Dayflow/DayflowTests/DayflowMultiDeviceTests.swift"
require_text 'static let shared = DayflowMultiDeviceViewModel()' "$repo_root/Dayflow/Dayflow/Core/MultiDevice/DayflowMultiDeviceViewModel.swift"
require_text 'DayflowMultiDeviceViewModel.shared' "$repo_root/Dayflow/Dayflow/App/AppDelegate.swift"
require_text 'DayflowMultiDeviceViewModel.shared' "$repo_root/Dayflow/Dayflow/Views/UI/Settings/SettingsMultiDeviceSection.swift"
require_text 'normalizedSharedSetting' "$repo_root/Dayflow/Dayflow/Core/MultiDevice/DayflowMacEventWriter.swift"
require_text 'testMacSharedSettingWriterNormalizesAndRejectsUnsafeValues' "$repo_root/Dayflow/DayflowTests/DayflowMultiDeviceTests.swift"
require_text 'isValidDatedSharedSettingKey' "$repo_root/Dayflow/Dayflow/Core/MultiDevice/DayflowMacEventWriter.swift"

require_text 'DayflowCoreBindings' "$repo_root/clients/ios/Package.swift"
require_text '../../shared-core/dist/DayflowCoreiOS.xcframework' "$repo_root/clients/ios/Package.swift"
require_text 'didConfigureRootView' "$repo_root/clients/ios/Sources/DayflowMobile/DayflowMobileApp.swift"
forbid_text '.task {' "$repo_root/clients/ios/Sources/DayflowMobile/DayflowMobileApp.swift"
require_text 'import DayflowCoreBindings' "$repo_root/clients/ios/Sources/DayflowMobile/DayflowCoreBridge.swift"
require_text 'func canonicalDeviceRequest' "$repo_root/clients/ios/Sources/DayflowMobile/DayflowCoreBridge.swift"
require_text 'core.canonicalDeviceRequest' "$repo_root/clients/ios/Sources/DayflowMobile/DayflowMobileSync.swift"

require_text 'compileSdk = 36' "$repo_root/clients/android/app/build.gradle.kts"
require_text 'java.srcDir("../../generated/kotlin")' "$repo_root/clients/android/app/build.gradle.kts"
require_text 'kotlin.srcDir("../../generated/kotlin")' "$repo_root/clients/android/app/build.gradle.kts"
require_text 'jniLibs.srcDir("../../generated/android/jniLibs")' "$repo_root/clients/android/app/build.gradle.kts"
require_text 'verifyDayflowCoreNative' "$repo_root/clients/android/app/build.gradle.kts"
require_text 'net.java.dev.jna:jna' "$repo_root/clients/android/app/build.gradle.kts"
forbid_text 'id("org.jetbrains.kotlin.android")' "$repo_root/clients/android/app/build.gradle.kts"
forbid_text 'id("org.jetbrains.kotlin.android")' "$repo_root/clients/android/build.gradle.kts"
require_text 'fallback_host_tag' "$repo_root/scripts/build_dayflow_core_android.sh"
require_text 'Native.register(UniffiLib::class.java' "$repo_root/clients/generated/kotlin/app/dayflow/core/dayflow_core.kt"
require_text 'fun canonicalDeviceRequest' "$repo_root/clients/android/app/src/main/java/app/dayflow/android/DayflowCoreBridge.kt"
require_text 'core.canonicalDeviceRequest' "$repo_root/clients/android/app/src/main/java/app/dayflow/android/DayflowAndroidSync.kt"
require_text 'FOREGROUND_SERVICE_MEDIA_PROJECTION' "$repo_root/clients/android/app/src/main/AndroidManifest.xml"
require_text 'android.hardware.touchscreen' "$repo_root/clients/android/app/src/main/AndroidManifest.xml"
require_text 'android:required="false"' "$repo_root/clients/android/app/src/main/AndroidManifest.xml"
require_text 'DayflowSyncWakeReceiver' "$repo_root/clients/android/app/src/main/AndroidManifest.xml"
require_text 'BIND_JOB_SERVICE' "$repo_root/clients/android/app/src/main/AndroidManifest.xml"
require_text 'fun syncIfConfigured()' "$repo_root/clients/android/app/src/main/java/app/dayflow/android/DayflowAndroidAccountSession.kt"
require_text 'suspend fun syncForPushWake()' "$repo_root/clients/android/app/src/main/java/app/dayflow/android/DayflowAndroidAccountSession.kt"
require_text 'DayflowSyncWakeContract.accepts' "$repo_root/clients/android/app/src/main/java/app/dayflow/android/DayflowSyncWakeReceiver.kt"
require_text 'acceptsScheduledExtras' "$repo_root/clients/android/app/src/main/java/app/dayflow/android/DayflowSyncWakeReceiver.kt"
require_text 'SYNC_AVAILABLE' "$repo_root/clients/android/app/src/main/java/app/dayflow/android/DayflowSyncWakeReceiver.kt"
require_text 'class DayflowSyncWakeJobService : JobService()' "$repo_root/clients/android/app/src/main/java/app/dayflow/android/DayflowSyncWakeReceiver.kt"
require_text 'fun captureAccountId(): String?' "$repo_root/clients/android/app/src/main/java/app/dayflow/android/DayflowAndroidAccountSession.kt"
require_text 'val workspace = activeWorkspaceId(current.accountId)' "$repo_root/clients/android/app/src/main/java/app/dayflow/android/DayflowAndroidAccountSession.kt"
require_text 'appModel.syncIfConfigured()' "$repo_root/clients/android/app/src/main/java/app/dayflow/android/MainActivity.kt"
require_text 'startCapture(appModel.captureAccountId())' "$repo_root/clients/android/app/src/main/java/app/dayflow/android/MainActivity.kt"
require_text 'DayflowAndroidProductSurface' "$repo_root/clients/android/app/src/main/java/app/dayflow/android/MainActivity.kt"
require_text 'privacy_gated_local_visual_v1' "$repo_root/clients/android/app/src/main/java/app/dayflow/android/capture/DayflowLocalVisualDeriver.kt"
require_text 'derivationMode: String = "privacy_gated_local_visual_v1"' "$repo_root/clients/android/app/src/main/java/app/dayflow/android/DayflowAndroidSync.kt"
require_text 'fun enqueueTombstone' "$repo_root/clients/android/app/src/main/java/app/dayflow/android/DayflowAndroidSync.kt"
require_text 'LOCAL_WORKSPACE_ID' "$repo_root/clients/android/app/src/main/java/app/dayflow/android/DayflowAndroidSync.kt"
require_text 'fun linkLocalWorkspace' "$repo_root/clients/android/app/src/main/java/app/dayflow/android/DayflowAndroidSync.kt"
require_text 'fun ensureLocalWorkspace' "$repo_root/clients/android/app/src/main/java/app/dayflow/android/DayflowAndroidSync.kt"
require_text 'ensureLogicalClockAtLeast' "$repo_root/clients/android/app/src/main/java/app/dayflow/android/DayflowLocalSyncStore.kt"
require_text 'immutable-ID preflight and INSERT in one transaction' "$repo_root/clients/android/app/src/main/java/app/dayflow/android/DayflowLocalSyncStore.kt"
require_text 'CURRENT_SCHEMA_VERSION' "$repo_root/clients/android/app/src/main/java/app/dayflow/android/DayflowEventEnvelope.kt"
require_text 'MAX_LOGICAL_CLOCK' "$repo_root/clients/android/app/src/main/java/app/dayflow/android/DayflowEventEnvelope.kt"
require_text 'hasValidEncryptedFieldShape' "$repo_root/clients/android/app/src/main/java/app/dayflow/android/DayflowEventEnvelope.kt"
require_text 'val store = DayflowLocalSyncStore(appContext, accountId)' "$repo_root/clients/android/app/src/main/java/app/dayflow/android/DayflowAndroidSync.kt"
require_text 'store.close()' "$repo_root/clients/android/app/src/main/java/app/dayflow/android/DayflowAndroidSync.kt"
require_text 'source mirror untouched' "$repo_root/clients/android/app/src/main/java/app/dayflow/android/DayflowAndroidSync.kt"
require_text 'resizeProjectionIfNeeded' "$repo_root/clients/android/app/src/main/java/app/dayflow/android/capture/DayflowCaptureService.kt"
require_text 'display.setSurface' "$repo_root/clients/android/app/src/main/java/app/dayflow/android/capture/DayflowCaptureService.kt"
require_text 'onCapturedContentResize' "$repo_root/clients/android/app/src/main/java/app/dayflow/android/capture/DayflowCaptureService.kt"
require_text '@Volatile' "$repo_root/clients/android/app/src/main/java/app/dayflow/android/capture/DayflowCaptureService.kt"
require_text 'private var contextJson' "$repo_root/clients/android/app/src/main/java/app/dayflow/android/capture/DayflowCaptureService.kt"
require_text 'markServiceHeartbeat' "$repo_root/clients/android/app/src/main/java/app/dayflow/android/capture/DayflowCaptureService.kt"
require_text 'SERVICE_HEARTBEAT_MAX_AGE_MILLIS' "$repo_root/clients/android/app/src/main/java/app/dayflow/android/capture/CaptureStatus.kt"
require_text 'staleCaptureStatusCannotPretendTheServiceIsStillRunning' "$repo_root/clients/android/app/src/test/java/app/dayflow/android/DayflowEventEnvelopeTest.kt"
require_text 'notificationCursor' "$repo_root/clients/android/app/src/main/java/app/dayflow/android/DayflowLocalSyncStore.kt"
require_text 'DayflowAndroidSyncHealthState' "$repo_root/clients/android/app/src/main/java/app/dayflow/android/DayflowLocalSyncStore.kt"
require_text 'recordSyncHealth' "$repo_root/clients/android/app/src/main/java/app/dayflow/android/DayflowLocalSyncStore.kt"
require_text 'appState.syncHealthSummary()' "$repo_root/clients/android/app/src/main/java/app/dayflow/android/MainActivity.kt"
require_text 'syncHealthSummary' "$repo_root/clients/android/app/src/main/java/app/dayflow/android/DayflowAndroidAccountSession.kt"
require_text 'DayflowNativeStatusKeys' "$repo_root/clients/android/app/src/main/java/app/dayflow/android/capture/CaptureStatus.kt"
require_text 'capture_permission' "$repo_root/clients/android/app/src/main/java/app/dayflow/android/capture/CaptureStatus.kt"
require_text 'statusFields' "$repo_root/clients/android/app/src/main/java/app/dayflow/android/MainActivity.kt"
require_text 'nativeStatusFieldsKeepCaptureAndDerivedSyncStateExplicit' "$repo_root/clients/android/app/src/test/java/app/dayflow/android/DayflowEventEnvelopeTest.kt"
require_text 'localVisualDerivationIsBoundedAndClassifiedWithoutRawPixels' "$repo_root/clients/android/app/src/test/java/app/dayflow/android/DayflowEventEnvelopeTest.kt"
require_text 'fun registerPushToken' "$repo_root/clients/android/app/src/main/java/app/dayflow/android/DayflowAndroidSync.kt"
require_text 'fun unregisterPushToken' "$repo_root/clients/android/app/src/main/java/app/dayflow/android/DayflowAndroidSync.kt"
require_text 'fun deleteJournalEntry' "$repo_root/clients/android/app/src/main/java/app/dayflow/android/DayflowAndroidAccountSession.kt"
require_text 'deleteTimelineCard' "$repo_root/clients/android/app/src/main/java/app/dayflow/android/MainActivity.kt"
require_text 'source = "android_media_projection"' "$repo_root/clients/android/app/src/main/java/app/dayflow/android/capture/DayflowCaptureService.kt"
require_text 'keyStore.hasAccountKeyAdmission(it)' "$repo_root/clients/android/app/src/main/java/app/dayflow/android/capture/DayflowCaptureService.kt"
require_text 'accountStore.load()?.accountId' "$repo_root/clients/android/app/src/main/java/app/dayflow/android/capture/DayflowCaptureService.kt"
require_text 'if (registration.keyBootstrapRequired)' "$repo_root/clients/android/app/src/main/java/app/dayflow/android/DayflowAndroidSync.kt"
require_text 'account-key-admitted-v1' "$repo_root/clients/android/app/src/main/java/app/dayflow/android/DayflowAndroidKeyStore.kt"
require_text 'keyStore.hasAccountKeyAdmission(it)' "$repo_root/clients/android/app/src/main/java/app/dayflow/android/DayflowAndroidAccountSession.kt"
require_text 'val workspace = captureWorkspaceId(accountId)' "$repo_root/clients/android/app/src/main/java/app/dayflow/android/DayflowAndroidSync.kt"
require_text '.commit()' "$repo_root/clients/android/app/src/main/java/app/dayflow/android/DayflowAndroidKeyStore.kt"
require_text 'markAccountKeyAdmitted' "$repo_root/clients/android/app/src/main/java/app/dayflow/android/DayflowAndroidSync.kt"
require_text 'SCREEN_OFF_ACTION' "$repo_root/clients/android/app/src/main/java/app/dayflow/android/capture/CaptureStatus.kt"
require_text 'SHUTDOWN_ACTION' "$repo_root/clients/android/app/src/main/java/app/dayflow/android/capture/CaptureStatus.kt"
require_text 'deviceAllowsCapture' "$repo_root/clients/android/app/src/main/java/app/dayflow/android/capture/DayflowCaptureService.kt"
require_text 'systemLockAndSleepSignalsStopCaptureWithoutResumingIt' "$repo_root/clients/android/app/src/test/java/app/dayflow/android/DayflowEventEnvelopeTest.kt"
require_text 'syncWakeAcceptsOnlyTheContentFreeAvailabilitySignal' "$repo_root/clients/android/app/src/test/java/app/dayflow/android/DayflowEventEnvelopeTest.kt"
require_text 'testRemoteNotificationWakeRequiresAnExactSilentPayload' "$repo_root/clients/ios/Tests/DayflowMobileTests/DayflowMobileTests.swift"
require_text 'testGeneratedRustBridgeMatchesCanonicalRequestVector' "$repo_root/clients/ios/Tests/DayflowMobileTests/DayflowMobileTests.swift"
require_text 'testGeneratedRustBridgeMatchesCanonicalRequestVector' "$repo_root/Dayflow/DayflowTests/DayflowMultiDeviceTests.swift"
require_text 'testGeneratedRustBridgeRecoveryKitRetainsKeyVersionsAndRejectsWrongPassphrase' "$repo_root/clients/ios/Tests/DayflowMobileTests/DayflowMobileTests.swift"
require_text 'static func accepts' "$repo_root/clients/ios/Sources/DayflowMobile/DayflowMobilePushWakeContract.swift"
require_text 'keystoreCommitIsReadableBeforeTheSyncReturns' "$repo_root/clients/android/app/src/androidTest/java/app/dayflow/android/DayflowCoreBindingInstrumentedTest.kt"
require_text 'physicalDeviceIdentityIsStableAcrossSessionInstances' "$repo_root/clients/android/app/src/androidTest/java/app/dayflow/android/DayflowCoreBindingInstrumentedTest.kt"
require_text 'generatedBindingRecoveryKitRetainsKeyVersionsAndRejectsWrongPassphrase' "$repo_root/clients/android/app/src/androidTest/java/app/dayflow/android/DayflowCoreBindingInstrumentedTest.kt"
require_text 'generatedBindingMatchesCanonicalRequestVector' "$repo_root/clients/android/app/src/androidTest/java/app/dayflow/android/DayflowCoreBindingInstrumentedTest.kt"
require_text 'localStoreSyncHealthPersistsBoundedStateAcrossReopen' "$repo_root/clients/android/app/src/androidTest/java/app/dayflow/android/DayflowCoreBindingInstrumentedTest.kt"
require_text 'dayflow.capture.paused' "$repo_root/clients/android/app/src/main/java/app/dayflow/android/capture/CaptureStatus.kt"
require_text 'fromSignals' "$repo_root/clients/android/app/src/main/java/app/dayflow/android/ChromeOsCapabilities.kt"
require_text 'resizedChromeOsWindowKeepsArcIdentityButUpdatesLayoutFlags' "$repo_root/clients/android/app/src/test/java/app/dayflow/android/ChromeOsCapabilitiesTest.kt"
require_text 'no raw frame is written to disk or sent to the relay.' "$repo_root/clients/android/app/src/main/java/app/dayflow/android/capture/DayflowCaptureService.kt"
require_text 'android:networkSecurityConfig="@xml/network_security_config"' "$repo_root/clients/android/app/src/main/AndroidManifest.xml"
forbid_text 'android:usesCleartextTraffic="true"' "$repo_root/clients/android/app/src/main/AndroidManifest.xml"
require_text '<base-config cleartextTrafficPermitted="false" />' "$repo_root/clients/android/app/src/main/res/xml/network_security_config.xml"
require_text '<domain-config cleartextTrafficPermitted="true">' "$repo_root/clients/android/app/src/main/res/xml/network_security_config.xml"
forbid_text '<base-config cleartextTrafficPermitted="true"' "$repo_root/clients/android/app/src/main/res/xml/network_security_config.xml"
require_text '<domain includeSubdomains="false">localhost</domain>' "$repo_root/clients/android/app/src/main/res/xml/network_security_config.xml"
require_text '<domain includeSubdomains="false">127.0.0.1</domain>' "$repo_root/clients/android/app/src/main/res/xml/network_security_config.xml"
require_text '<domain includeSubdomains="false">[::1]</domain>' "$repo_root/clients/android/app/src/main/res/xml/network_security_config.xml"

require_text 'DayflowPackaging' "$repo_root/clients/windows/Dayflow.Windows/Dayflow.Windows.csproj"
require_text 'MSIX</WindowsPackageType>' "$repo_root/clients/windows/Dayflow.Windows/Dayflow.Windows.csproj"
require_text 'None</WindowsPackageType>' "$repo_root/clients/windows/Dayflow.Windows/Dayflow.Windows.csproj"
require_text 'EnableMsixTooling' "$repo_root/clients/windows/Dayflow.Windows/Dayflow.Windows.csproj"
require_text 'Dayflow.Windows' "$repo_root/clients/windows/Dayflow.Windows/Package.appxmanifest"
require_text 'Square150x150Logo' "$repo_root/clients/windows/Dayflow.Windows/Package.appxmanifest"
require_text 'GenerateAppxPackageOnBuild' "$repo_root/clients/windows/Dayflow.Windows/Properties/PublishProfiles/win10-x64.pubxml"
require_text 'LocalApplicationData' "$repo_root/clients/windows/Dayflow.Windows/Core/DayflowWindowsStorage.cs"
require_text 'Flush(flushToDisk: true)' "$repo_root/clients/windows/Dayflow.Windows/Core/DayflowWindowsKeyStore.cs"
require_text 'File.Replace(temporaryPath, path' "$repo_root/clients/windows/Dayflow.Windows/Core/DayflowWindowsKeyStore.cs"
forbid_text 'ApplicationData.Current' "$repo_root/clients/windows/Dayflow.Windows"
require_text 'RequireDayflowCoreNative' "$repo_root/clients/windows/Dayflow.Windows/Dayflow.Windows.csproj"
require_text 'dayflow_core.dll' "$repo_root/clients/windows/Dayflow.Windows/Dayflow.Windows.csproj"
require_text 'dayflow_core' "$repo_root/clients/windows/Dayflow.Windows/Core/DayflowCoreInterop.cs"
require_text 'dayflow_core_canonical_device_request_json' "$repo_root/clients/windows/Dayflow.Windows/Core/DayflowCoreInterop.cs"
require_text 'ReadSuccessfulJson' "$repo_root/clients/windows/Dayflow.Windows/Core/DayflowCoreInterop.cs"
require_text 'CultureInfo.InvariantCulture' "$repo_root/clients/windows/Dayflow.Windows/Core/DayflowWindowsSyncClient.cs"
require_text 'DayflowCoreInterop.CanonicalDeviceRequest' "$repo_root/clients/windows/Dayflow.Windows/Core/DayflowWindowsSyncClient.cs"
forbid_text 'timestamp.ToString()' "$repo_root/clients/windows/Dayflow.Windows/Core/DayflowWindowsSyncClient.cs"
require_text 'CAbiRecoveryErrorsDoNotPassThroughAsSuccessfulJson' "$repo_root/clients/windows/Dayflow.Windows.Tests/DayflowCoreInteropTests.cs"
require_text 'CAbiCanonicalRequestMatchesTheWireVector' "$repo_root/clients/windows/Dayflow.Windows.Tests/DayflowCoreInteropTests.cs"
require_text 'DpapiKeyStoreRoundTripsAndCleansUpAnAtomicWrite' "$repo_root/clients/windows/Dayflow.Windows.Tests/DayflowCoreInteropTests.cs"
require_text 'SyncIfConfiguredAsync' "$repo_root/clients/windows/Dayflow.Windows/Core/DayflowWindowsAccountSession.cs"
require_text 'DayflowWindowsEndpointPolicy.IsAllowed(uri)' "$repo_root/clients/windows/Dayflow.Windows/Core/DayflowWindowsAccountSession.cs"
require_text 'MainWindow_Activated' "$repo_root/clients/windows/Dayflow.Windows/MainWindow.xaml.cs"
require_text 'derivationMode = "privacy_gated_foreground_metadata"' "$repo_root/clients/windows/Dayflow.Windows/Core/DayflowWindowsSyncSession.cs"
require_text 'MetadataOnlyDescription' "$repo_root/clients/windows/Dayflow.Windows/Core/DayflowWindowsCapturePolicy.cs"
require_text 'MetadataOnlyCaptureDescriptionDoesNotSyncWindowTitles' "$repo_root/clients/windows/Dayflow.Windows.Tests/DayflowCoreInteropTests.cs"
require_text 'privacy_gated_local_context_v1' "$repo_root/clients/windows/Dayflow.Windows/Core/DayflowWindowsCapturePolicy.cs"
require_text 'DayflowWindowsPrivacyPreferences' "$repo_root/clients/windows/Dayflow.Windows/Core/DayflowWindowsPrivacyPreferences.cs"
require_text 'UpdatePrivacyPreferences' "$repo_root/clients/windows/Dayflow.Windows/Capture/WindowsCaptureAdapter.cs"
require_text 'LocalDerivationProducesMeaningfulCardsWithoutWindowTitleLeakage' "$repo_root/clients/windows/Dayflow.Windows.Tests/DayflowCoreInteropTests.cs"
require_text 'EnqueueTombstone' "$repo_root/clients/windows/Dayflow.Windows/Core/DayflowWindowsSyncSession.cs"
require_text 'LocalWorkspaceId' "$repo_root/clients/windows/Dayflow.Windows/Core/DayflowWindowsSyncSession.cs"
require_text 'LinkLocalWorkspace' "$repo_root/clients/windows/Dayflow.Windows/Core/DayflowWindowsSyncSession.cs"
require_text 'EnsureLocalWorkspace' "$repo_root/clients/windows/Dayflow.Windows/Core/DayflowWindowsSyncSession.cs"
require_text 'EnsureLogicalClockAtLeast' "$repo_root/clients/windows/Dayflow.Windows/Core/DayflowLocalSyncStore.cs"
require_text 'immutable-ID preflight and INSERT atomic' "$repo_root/clients/windows/Dayflow.Windows/Core/DayflowLocalSyncStore.cs"
require_text 'The event key version must be positive.' "$repo_root/clients/windows/Dayflow.Windows/Core/DayflowLocalSyncStore.cs"
require_text 'CurrentSchemaVersion' "$repo_root/clients/windows/Dayflow.Windows/Core/DayflowEventEnvelope.cs"
require_text 'MaxLogicalClock' "$repo_root/clients/windows/Dayflow.Windows/Core/DayflowEventEnvelope.cs"
require_text 'HasValidEncryptedFieldShape' "$repo_root/clients/windows/Dayflow.Windows/Core/DayflowEventEnvelope.cs"
require_text 'source mirror untouched' "$repo_root/clients/windows/Dayflow.Windows/Core/DayflowWindowsSyncSession.cs"
require_text 'NotificationCursor' "$repo_root/clients/windows/Dayflow.Windows/Core/DayflowLocalSyncStore.cs"
require_text 'RegisterPushTokenAsync' "$repo_root/clients/windows/Dayflow.Windows/Core/DayflowWindowsSyncClient.cs"
require_text 'UnregisterPushTokenAsync' "$repo_root/clients/windows/Dayflow.Windows/Core/DayflowWindowsSyncClient.cs"
require_text 'AcceptsSyncAvailablePayload' "$repo_root/clients/windows/Dayflow.Windows/Core/DayflowWindowsPushNotifications.cs"
require_text 'CreatePushNotificationChannelForApplicationAsync' "$repo_root/clients/windows/Dayflow.Windows/Core/DayflowWindowsPushNotifications.cs"
require_text 'SyncForPushWakeAsync' "$repo_root/clients/windows/Dayflow.Windows/Core/DayflowWindowsAccountSession.cs"
require_text 'TryRegisterPushChannelAsync' "$repo_root/clients/windows/Dayflow.Windows/Core/DayflowWindowsAccountSession.cs"
require_text 'WindowsPushWakeAcceptsOnlyTheContentFreeAvailabilitySignal' "$repo_root/clients/windows/Dayflow.Windows.Tests/DayflowCoreInteropTests.cs"
require_text 'CAbiVersionedRecoveryKitRetainsKeyVersionsAndRejectsWrongPassphrase' "$repo_root/clients/windows/Dayflow.Windows.Tests/DayflowCoreInteropTests.cs"
require_text 'DayflowWindowsSyncHealthState' "$repo_root/clients/windows/Dayflow.Windows/Core/DayflowLocalSyncStore.cs"
require_text 'RecordSyncHealth' "$repo_root/clients/windows/Dayflow.Windows/Core/DayflowLocalSyncStore.cs"
require_text 'SyncHealthSummary' "$repo_root/clients/windows/Dayflow.Windows/Core/DayflowWindowsAccountSession.cs"
require_text 'SyncHealthText' "$repo_root/clients/windows/Dayflow.Windows/MainWindow.xaml"
require_text 'LocalStoreSyncHealthPersistsBoundedStateAcrossReopen' "$repo_root/clients/windows/Dayflow.Windows.Tests/DayflowCoreInteropTests.cs"
require_text 'WindowsCaptureStatusFields' "$repo_root/clients/windows/Dayflow.Windows/Capture/WindowsCaptureAdapter.cs"
require_text 'capture_permission' "$repo_root/clients/windows/Dayflow.Windows/Capture/WindowsCaptureAdapter.cs"
require_text 'CapturePermissionText' "$repo_root/clients/windows/Dayflow.Windows/MainWindow.xaml"
require_text 'NativeStatusFieldsKeepCaptureAndDerivedSyncStateExplicit' "$repo_root/clients/windows/Dayflow.Windows.Tests/DayflowCoreInteropTests.cs"
require_text 'WindowsPushWakeAcceptsOnlyTheContentFreeAvailabilitySignal' "$repo_root/clients/windows/Dayflow.Windows.Tests/DayflowCoreInteropTests.cs"
require_text 'DeleteJournalEntry' "$repo_root/clients/windows/Dayflow.Windows/Core/DayflowWindowsAccountSession.cs"
require_text 'TimelineRecordsPanel' "$repo_root/clients/windows/Dayflow.Windows/MainWindow.xaml"
require_text 'windows_graphics_capture' "$repo_root/clients/windows/Dayflow.Windows/Core/DayflowWindowsAccountSession.cs"
require_text 'if (registration.KeyBootstrapRequired)' "$repo_root/clients/windows/Dayflow.Windows/Core/DayflowWindowsSyncSession.cs"
require_text 'account-key-admitted-v1' "$repo_root/clients/windows/Dayflow.Windows/Core/DayflowWindowsKeyStore.cs"
require_text '_keyStore.HasAccountKeyAdmission(AccountId)' "$repo_root/clients/windows/Dayflow.Windows/Core/DayflowWindowsAccountSession.cs"
require_text 'var workspace = CaptureWorkspaceId(accountId)' "$repo_root/clients/windows/Dayflow.Windows/Core/DayflowWindowsSyncSession.cs"
require_text 'MarkAccountKeyAdmitted' "$repo_root/clients/windows/Dayflow.Windows/Core/DayflowWindowsSyncSession.cs"
require_text 'raw pixels never enter the event writer.' "$repo_root/clients/windows/Dayflow.Windows/Capture/WindowsCaptureAdapter.cs"
require_text 'UpdateSharedCapturePause' "$repo_root/clients/windows/Dayflow.Windows/Capture/WindowsCaptureAdapter.cs"
require_text 'SharedCapturePauseParsingFailsClosed' "$repo_root/clients/windows/Dayflow.Windows.Tests/DayflowCoreInteropTests.cs"
require_text 'DayflowWindowsCapturePolicy.cs' "$repo_root/clients/windows/Dayflow.Windows.Tests/Dayflow.Windows.Tests.csproj"
require_text 'SharedEndpointPolicyRejectsCredentialAndQueryBearingRelayUrls' "$repo_root/clients/windows/Dayflow.Windows.Tests/DayflowCoreInteropTests.cs"
require_text 'DayflowWindowsSharedSettingContract.IsAllowedKey' "$repo_root/clients/windows/Dayflow.Windows/Core/DayflowWindowsSyncSession.cs"
require_text 'SharedSettingContractRejectsMalformedDatedKeys' "$repo_root/clients/windows/Dayflow.Windows.Tests/DayflowCoreInteropTests.cs"
require_text 'ReferenceEquals(_framePool, sender)' "$repo_root/clients/windows/Dayflow.Windows/Capture/WindowsGraphicsCaptureFramePipeline.cs"
require_text 'Stop/close can win the race' "$repo_root/clients/windows/Dayflow.Windows/Capture/WindowsGraphicsCaptureFramePipeline.cs"

require_text 'func syncIfConfigured()' "$repo_root/clients/ios/Sources/DayflowMobile/DayflowMobileAccountSession.swift"
require_text 'DayflowMobileSyncHealthState' "$repo_root/clients/ios/Sources/DayflowMobile/DayflowLocalSyncStore.swift"
require_text 'recordSyncHealth' "$repo_root/clients/ios/Sources/DayflowMobile/DayflowMobileSync.swift"
require_text 'syncHealthSummary' "$repo_root/clients/ios/Sources/DayflowMobile/DayflowMobileAccountSession.swift"
require_text 'testLocalSQLiteSyncHealthPersistsBoundedStateAcrossReopen' "$repo_root/clients/ios/Tests/DayflowMobileTests/DayflowMobileTests.swift"
require_text 'DayflowNativeStatusKey' "$repo_root/clients/ios/Sources/DayflowMobile/Capture/ActivityCaptureSession.swift"
require_text 'capture_permission' "$repo_root/clients/ios/Sources/DayflowMobile/Capture/ActivityCaptureSession.swift"
require_text 'captureStatusFields' "$repo_root/clients/ios/Sources/DayflowMobile/DayflowRootView.swift"
require_text 'testNativeStatusFieldsKeepCaptureAndDerivedSyncStateExplicit' "$repo_root/clients/ios/Tests/DayflowMobileTests/DayflowMobileTests.swift"
require_text '-scheme DayflowMobileApp' "$repo_root/.github/workflows/dayflow-native-clients.yml"
require_text 'name = DayflowMobileApp;' "$repo_root/clients/ios/DayflowMobile.xcodeproj/project.pbxproj"
require_text 'PRODUCT_MODULE_NAME = DayflowMobileApp;' "$repo_root/clients/ios/DayflowMobile.xcodeproj/project.pbxproj"
require_text 'BlueprintName = "DayflowMobileApp"' "$repo_root/clients/ios/DayflowMobile.xcodeproj/xcshareddata/xcschemes/DayflowMobileApp.xcscheme"
require_text 'Build the iOS application target' "$repo_root/.github/workflows/dayflow-native-clients.yml"
require_text "generic/platform=iOS Simulator" "$repo_root/.github/workflows/dayflow-native-clients.yml"
require_text 'Build unsigned macOS DMG artifact' "$repo_root/.github/workflows/dayflow-native-clients.yml"
require_text 'hdiutil create' "$repo_root/.github/workflows/dayflow-native-clients.yml"
require_text 'dayflow-macos-dmg' "$repo_root/.github/workflows/dayflow-native-clients.yml"
require_text 'Build unsigned iOS archive artifact' "$repo_root/.github/workflows/dayflow-native-clients.yml"
require_text 'dayflow-ios-unsigned-archive' "$repo_root/.github/workflows/dayflow-native-clients.yml"
forbid_text 'SDKROOT = iphoneos' "$repo_root/clients/ios/DayflowMobile.xcodeproj/project.pbxproj"
require_text 'appModel.syncIfConfigured()' "$repo_root/clients/ios/Sources/DayflowMobile/DayflowMobileApp.swift"
require_text 'DayflowMobileAppDelegate.self' "$repo_root/clients/ios/Sources/DayflowMobile/DayflowMobileApp.swift"
require_text 'requestRemoteNotificationRegistration()' "$repo_root/clients/ios/Sources/DayflowMobile/DayflowMobileApp.swift"
require_text 'didRegisterForRemoteNotificationsWithDeviceToken' "$repo_root/clients/ios/Sources/DayflowMobile/DayflowMobilePushNotifications.swift"
require_text 'didReceiveRemoteNotification' "$repo_root/clients/ios/Sources/DayflowMobile/DayflowMobilePushNotifications.swift"
require_text 'syncForPushWake()' "$repo_root/clients/ios/Sources/DayflowMobile/DayflowMobilePushNotifications.swift"
require_text 'DayflowMobilePushWakeContract.accepts' "$repo_root/clients/ios/Sources/DayflowMobile/DayflowMobilePushNotifications.swift"
require_text 'remote-notification' "$repo_root/clients/ios/DayflowMobileApp/Info.plist"
require_text 'aps-environment' "$repo_root/clients/ios/DayflowMobileApp/DayflowMobileApp.entitlements"
require_text 'APS_ENVIRONMENT' "$repo_root/clients/ios/DayflowMobile.xcodeproj/project.pbxproj"
require_text 'derivationMode: String = "privacy_gated_local_metadata"' "$repo_root/clients/ios/Sources/DayflowMobile/DayflowMobileSync.swift"
require_text 'enqueueTombstone' "$repo_root/clients/ios/Sources/DayflowMobile/DayflowMobileSync.swift"
require_text 'localWorkspaceID' "$repo_root/clients/ios/Sources/DayflowMobile/DayflowMobileSync.swift"
require_text 'linkLocalWorkspace' "$repo_root/clients/ios/Sources/DayflowMobile/DayflowMobileSync.swift"
require_text 'ensureLocalWorkspace' "$repo_root/clients/ios/Sources/DayflowMobile/DayflowMobileSync.swift"
require_text 'ensureLogicalClock(atLeast value:' "$repo_root/clients/ios/Sources/DayflowMobile/DayflowLocalSyncStore.swift"
require_text 'immutable-ID preflight and INSERT atomic' "$repo_root/clients/ios/Sources/DayflowMobile/DayflowLocalSyncStore.swift"
require_text 'currentSchemaVersion' "$repo_root/clients/ios/Sources/DayflowMobile/DayflowEventEnvelope.swift"
require_text 'maxLogicalClock' "$repo_root/clients/ios/Sources/DayflowMobile/DayflowEventEnvelope.swift"
require_text 'hasValidEncryptedFieldShape' "$repo_root/clients/ios/Sources/DayflowMobile/DayflowEventEnvelope.swift"
require_text 'source mirror untouched' "$repo_root/clients/ios/Sources/DayflowMobile/DayflowMobileSync.swift"
require_text 'notificationCursor' "$repo_root/clients/ios/Sources/DayflowMobile/DayflowLocalSyncStore.swift"
require_text 'registerPushToken' "$repo_root/clients/ios/Sources/DayflowMobile/DayflowMobileSync.swift"
require_text 'unregisterPushToken' "$repo_root/clients/ios/Sources/DayflowMobile/DayflowMobileSync.swift"
require_text 'restoreActiveWorkspace' "$repo_root/clients/ios/Sources/DayflowMobile/DayflowMobileAccountSession.swift"
require_text 'deleteJournalEntry' "$repo_root/clients/ios/Sources/DayflowMobile/DayflowMobileAccountSession.swift"
require_text 'Saved records' "$repo_root/clients/ios/Sources/DayflowMobile/DayflowRootView.swift"
require_text 'source: "ios_replaykit"' "$repo_root/clients/ios/Sources/DayflowMobile/DayflowMobileAccountSession.swift"
require_text 'registration.keyBootstrapRequired == true' "$repo_root/clients/ios/Sources/DayflowMobile/DayflowMobileSync.swift"
require_text 'account-key-admitted-v1' "$repo_root/clients/ios/Sources/DayflowMobile/DayflowMobileKeyStore.swift"
require_text 'keyStore.hasAccountKeyAdmission(accountID: accountSession.accountID)' "$repo_root/clients/ios/Sources/DayflowMobile/DayflowMobileAccountSession.swift"
require_text 'let workspace = captureWorkspaceID(accountID)' "$repo_root/clients/ios/Sources/DayflowMobile/DayflowMobileSync.swift"
require_text 'let activeWorkspace = activeWorkspaceID()' "$repo_root/clients/ios/Sources/DayflowMobile/DayflowMobileAccountSession.swift"
require_text 'markAccountKeyAdmitted' "$repo_root/clients/ios/Sources/DayflowMobile/DayflowMobileSync.swift"
require_text 'Raw ReplayKit buffers never leave this object.' "$repo_root/clients/ios/Sources/DayflowMobile/Capture/ActivityCaptureSession.swift"
require_text 'completionHandler:' "$repo_root/clients/ios/Sources/DayflowMobile/Capture/ActivityCaptureSession.swift"
require_text 'sharedCapturePauseEnabled' "$repo_root/clients/ios/Sources/DayflowMobile/Capture/ActivityCaptureSession.swift"
require_text 'testSharedCapturePauseParsingFailsClosed' "$repo_root/clients/ios/Tests/DayflowMobileTests/DayflowMobileTests.swift"
require_text 'let frameGate = self.frameGate' "$repo_root/clients/ios/Sources/DayflowMobile/Capture/ActivityCaptureSession.swift"
require_text 'guard frameGate.shouldHandle(now: now)' "$repo_root/clients/ios/Sources/DayflowMobile/Capture/ActivityCaptureSession.swift"
require_text 'func syncIfConfigured()' "$repo_root/Dayflow/Dayflow/Core/MultiDevice/DayflowMultiDeviceViewModel.swift"
require_text 'multiDeviceSync.syncIfConfigured()' "$repo_root/Dayflow/Dayflow/App/AppDelegate.swift"
require_text 'registration.keyBootstrapRequired == true' "$repo_root/Dayflow/Dayflow/Core/MultiDevice/DayflowMultiDeviceViewModel.swift"
require_text 'account-key-admitted-v1' "$repo_root/Dayflow/Dayflow/Core/MultiDevice/DayflowMultiDeviceKeyStore.swift"
require_text 'keyStore.hasAccountKeyAdmission' "$repo_root/Dayflow/Dayflow/Core/MultiDevice/DayflowMacEventWriter.swift"
require_text 'Finish encrypted sync admission' "$repo_root/Dayflow/Dayflow/Core/MultiDevice/DayflowMultiDeviceViewModel.swift"
require_text 'markAccountKeyAdmitted' "$repo_root/Dayflow/Dayflow/Core/MultiDevice/DayflowMultiDeviceViewModel.swift"
require_text 'dayflowSharedCapturePauseChanged' "$repo_root/Dayflow/Dayflow/App/DayflowApp.swift"
require_text 'DayflowSharedCapturePause' "$repo_root/Dayflow/Dayflow/Core/MultiDevice/DayflowProjectionImporter.swift"
require_text 'setSharedCapturePaused' "$repo_root/Dayflow/Dayflow/Core/MultiDevice/DayflowMultiDeviceViewModel.swift"
require_text 'Pause across devices' "$repo_root/Dayflow/Dayflow/Views/UI/Settings/SettingsMultiDeviceSection.swift"
require_text 'DayflowMacStatusFields' "$repo_root/Dayflow/Dayflow/Core/MultiDevice/DayflowMultiDeviceViewModel.swift"
require_text 'capture_permission' "$repo_root/Dayflow/Dayflow/Core/MultiDevice/DayflowMultiDeviceViewModel.swift"
require_text 'nativeStatusFields' "$repo_root/Dayflow/Dayflow/Views/UI/Settings/SettingsMultiDeviceSection.swift"
require_text 'testMacStatusFieldsExposeTheNativeStatusContract' "$repo_root/Dayflow/DayflowTests/DayflowMultiDeviceTests.swift"
require_text 'sharedCapturePaused' "$repo_root/Dayflow/Dayflow/Core/Recording/ScreenRecorder.swift"
require_text 'func logicalDayKey(' "$repo_root/Dayflow/Dayflow/Core/MultiDevice/DayflowCoreBridge.swift"
require_text 'logicalDay: String? = nil' "$repo_root/Dayflow/Dayflow/Core/MultiDevice/DayflowEventPayloadEncoder.swift"
require_text 'forUnixTimestamp:' "$repo_root/Dayflow/Dayflow/Core/MultiDevice/DayflowMacEventWriter.swift"
require_text 'testMacRustLogicalDayBridgeUsesFourAMBoundary' "$repo_root/Dayflow/DayflowTests/DayflowMultiDeviceTests.swift"
forbid_text 'DayflowMultiDeviceAccountScope.current!' "$repo_root/Dayflow/Dayflow/Core/MultiDevice/DayflowMacEventWriter.swift"
require_text 'testSharedCapturePauseParsingFailsClosed' "$repo_root/Dayflow/DayflowTests/DayflowMultiDeviceTests.swift"
require_text 'pullNotificationHints' "$repo_root/Dayflow/Dayflow/Core/MultiDevice/DayflowSyncRelayClient.swift"
require_text 'registerPushToken' "$repo_root/Dayflow/Dayflow/Core/MultiDevice/DayflowSyncRelayClient.swift"
require_text 'unregisterPushToken' "$repo_root/Dayflow/Dayflow/Core/MultiDevice/DayflowSyncRelayClient.swift"
require_text 'DayflowCoreBridge.shared.canonicalDeviceRequest' "$repo_root/Dayflow/Dayflow/Core/MultiDevice/DayflowSyncRelayClient.swift"
require_text 'notification_cursor' "$repo_root/Dayflow/Dayflow/Core/MultiDevice/DayflowLocalSyncStore.swift"
require_text 'ensureMultiDeviceLogicalClock' "$repo_root/Dayflow/Dayflow/Core/MultiDevice/DayflowLocalSyncStore.swift"
require_text 'maxLogicalClock' "$repo_root/Dayflow/Dayflow/Core/MultiDevice/DayflowSyncModels.swift"
require_text 'hasValidEncryptedFieldShape' "$repo_root/Dayflow/Dayflow/Core/MultiDevice/DayflowSyncModels.swift"
require_text 'DayflowBackendHTTP.noRedirectSession' "$repo_root/Dayflow/Dayflow/Core/AI/DayflowBackendProvider.swift"
require_text 'DayflowBackendConfiguration.validatedEndpointURL' "$repo_root/Dayflow/Dayflow/Core/AI/DayflowBackendProvider.swift"
require_text 'authorizedRequest(url:' "$repo_root/Dayflow/Dayflow/Core/AI/GeminiDirectProvider.swift"
require_text 'testMacGeminiProviderKeepsAPIKeyOutOfURLQuery' "$repo_root/Dayflow/DayflowTests/DayflowMultiDeviceTests.swift"
require_text 'x-goog-api-key' "$repo_root/Dayflow/Dayflow/Core/AI/GeminiDirectProvider.swift"
require_text 'x-goog-api-key' "$repo_root/Dayflow/Dayflow/Utilities/GeminiAPIHelper.swift"
forbid_text '?key=' "$repo_root/Dayflow/Dayflow"
require_text 'DayflowAndroidEndpointPolicy.isAllowed' "$repo_root/clients/android/app/src/main/java/app/dayflow/android/DayflowAIProviderConfiguration.kt"
require_text 'uri.encodedQuery != null' "$repo_root/clients/android/app/src/main/java/app/dayflow/android/DayflowAIProviderConfiguration.kt"
require_text 'x-goog-api-key' "$repo_root/clients/android/app/src/main/java/app/dayflow/android/DayflowAndroidAIChat.kt"
forbid_text '?key=' "$repo_root/clients/android/app/src/main/java/app/dayflow/android/DayflowAndroidAIChat.kt"
require_text 'setRequestProperty("Cookie", "")' "$repo_root/clients/android/app/src/main/java/app/dayflow/android/DayflowAndroidSync.kt"
require_text 'DayflowWindowsEndpointPolicy.IsAllowed' "$repo_root/clients/windows/Dayflow.Windows/Core/DayflowWindowsAuthClient.cs"
require_text 'UseCookies = false' "$repo_root/clients/windows/Dayflow.Windows/Core/DayflowWindowsAIChatClient.cs"
require_text 'x-goog-api-key' "$repo_root/clients/windows/Dayflow.Windows/Core/DayflowWindowsAIChatClient.cs"
forbid_text 'AddQuery' "$repo_root/clients/windows/Dayflow.Windows/Core/DayflowWindowsAIChatClient.cs"
require_text 'DayflowMobileHTTP.isAllowedEndpoint' "$repo_root/clients/ios/Sources/DayflowMobile/DayflowAIProviderConfiguration.swift"
require_text 'x-goog-api-key' "$repo_root/clients/ios/Sources/DayflowMobile/DayflowMobileAIChat.swift"
forbid_text 'addQueryItem' "$repo_root/clients/ios/Sources/DayflowMobile/DayflowMobileAIChat.swift"

# Shared setting namespaces must remain authorable on every native client. The
# Mac migration emits daily_standup snapshots, so another device must be able
# to edit/re-emit that encrypted projection without taking a platform-specific
# path.
require_text 'DayflowAndroidSharedSettingContract.isAllowedKey' "$repo_root/clients/android/app/src/main/java/app/dayflow/android/DayflowAndroidSync.kt"
require_text 'sharedSettingContractRejectsMalformedDatedKeys' "$repo_root/clients/android/app/src/test/java/app/dayflow/android/DayflowEventEnvelopeTest.kt"
require_text 'daily_standup:' "$repo_root/clients/windows/Dayflow.Windows/Core/DayflowWindowsSharedSettingContract.cs"
require_text 'DayflowWindowsSharedSettingContract.cs' "$repo_root/clients/windows/Dayflow.Windows.Tests/Dayflow.Windows.Tests.csproj"
require_text 'DayflowMobileSharedSettingContract.isAllowedKey' "$repo_root/clients/ios/Sources/DayflowMobile/DayflowMobileSync.swift"
require_text 'testSharedSettingContractRejectsMalformedDatedKeys' "$repo_root/clients/ios/Tests/DayflowMobileTests/DayflowMobileTests.swift"
require_text 'validatedEndpointURL' "$repo_root/Dayflow/Dayflow/System/DayflowBackendConfiguration.swift"
require_text 'DayflowAuthHTTP.noRedirectSession' "$repo_root/Dayflow/Dayflow/System/DayflowAuthManager.swift"
require_text 'key_bootstrap_grants' "$repo_root/companion-web/workers/api/src/relay-do.ts"
require_text 'DELETE FROM key_bootstrap_grants' "$repo_root/companion-web/workers/api/src/relay-do.ts"
require_text 'recovery admission is only allowed when no approved device remains' "$repo_root/companion-web/workers/api/src/relay-do.ts"
require_text 'rejects explicit recovery admission while an approved device remains' "$repo_root/companion-web/workers/api/src/relay-do.test.ts"
require_text 'identityURL.pathname = "/v1/me"' "$repo_root/companion-web/workers/api/src/auth.ts"
require_text 'principalFromResponse' "$repo_root/companion-web/workers/api/src/auth.ts"

require_text 'bash scripts/verify_dayflow_native_contracts.sh' "$repo_root/.github/workflows/dayflow-native-clients.yml"
require_text 'name: macOS app and non-interactive tests' "$repo_root/.github/workflows/dayflow-native-clients.yml"
require_text 'verify_dayflow_test_scheme.sh' "$repo_root/.github/workflows/dayflow-native-clients.yml"
forbid_text 'xcodebuild -project Dayflow/Dayflow.xcodeproj -list' "$repo_root/.github/workflows/dayflow-native-clients.yml"
require_text 'xcodebuild -quiet' "$repo_root/.github/workflows/dayflow-native-clients.yml"
require_text 'build_dayflow_core_ios_xcframework.sh' "$repo_root/.github/workflows/dayflow-native-clients.yml"
require_text 'build_dayflow_core_android.sh' "$repo_root/.github/workflows/dayflow-native-clients.yml"
require_text 'build_dayflow_core_windows.ps1' "$repo_root/.github/workflows/dayflow-native-clients.yml"
require_text 'gradle-version: "9.5.0"' "$repo_root/.github/workflows/dayflow-native-clients.yml"
require_text 'sdkmanager "platform-tools" "platforms;android-36"' "$repo_root/.github/workflows/dayflow-native-clients.yml"
require_text 'api-level: 35' "$repo_root/.github/workflows/dayflow-native-clients.yml"
require_text 'emulator-boot-timeout: 900' "$repo_root/.github/workflows/dayflow-native-clients.yml"
require_text 'id: android-emulator-smoke' "$repo_root/.github/workflows/dayflow-native-clients.yml"
require_text 'continue-on-error: true' "$repo_root/.github/workflows/dayflow-native-clients.yml"
require_text 'Retry Android UniFFI binding smoke test' "$repo_root/.github/workflows/dayflow-native-clients.yml"
require_text "if: steps.android-emulator-smoke.outcome == 'failure'" "$repo_root/.github/workflows/dayflow-native-clients.yml"
require_text 'emulator-options: -no-window -no-snapshot -noaudio -no-boot-anim -gpu swiftshader_indirect' "$repo_root/.github/workflows/dayflow-native-clients.yml"
require_text 'disable-animations: true' "$repo_root/.github/workflows/dayflow-native-clients.yml"
forbid_text 'platforms;android-37.0' "$repo_root/.github/workflows/dayflow-native-clients.yml"
require_text ':app:bundleRelease' "$repo_root/.github/workflows/dayflow-native-clients.yml"
require_text 'dayflow-android-release' "$repo_root/.github/workflows/dayflow-native-clients.yml"
require_text 'Build unsigned Windows MSIX package' "$repo_root/.github/workflows/dayflow-native-clients.yml"
require_text 'AppxPackageSigningEnabled=false' "$repo_root/.github/workflows/dayflow-native-clients.yml"
require_text 'Verify Windows package artifact' "$repo_root/.github/workflows/dayflow-native-clients.yml"
require_text 'dayflow-windows-msix' "$repo_root/.github/workflows/dayflow-native-clients.yml"
require_text 'Run Windows C-ABI smoke tests' "$repo_root/.github/workflows/dayflow-native-clients.yml"
require_text 'Run Android UniFFI binding smoke test' "$repo_root/.github/workflows/dayflow-native-clients.yml"
require_text 'androidTestImplementation("androidx.test.ext:junit:1.2.1")' "$repo_root/clients/android/app/build.gradle.kts"
require_text 'DayflowCoreBindingInstrumentedTest' "$repo_root/clients/android/app/src/androidTest/java/app/dayflow/android/DayflowCoreBindingInstrumentedTest.kt"

# A recovery restore must remain marked until the complete encrypted sync has
# succeeded. This is intentionally a source-order guard: clearing the marker
# immediately after registration makes a later network or projection failure
# retry as an ordinary device and can strand the restored account.
require_after \
  'try storage.recordMultiDeviceSync(state: .synced)' \
  'UserDefaults.standard.removeObject(forKey: recoveryRestorePendingKey)' \
  "$repo_root/Dayflow/Dayflow/Core/MultiDevice/DayflowMultiDeviceViewModel.swift"
require_after \
  'try store.recordSyncHealth(.synced)' \
  'UserDefaults.standard.removeObject(forKey: Self.recoveryRestorePendingKey(accountID: accountID))' \
  "$repo_root/clients/ios/Sources/DayflowMobile/DayflowMobileSync.swift"
require_after \
  'store.recordSyncHealth(DayflowAndroidSyncHealthState.SYNCED)' \
  'recoveryPreferences.edit().remove(accountId).commit()' \
  "$repo_root/clients/android/app/src/main/java/app/dayflow/android/DayflowAndroidSync.kt"
require_after \
  'store.RecordSyncHealth(DayflowWindowsSyncHealthState.Synced)' \
  'ClearRecoveryRestorePending(accountId)' \
  "$repo_root/clients/windows/Dayflow.Windows/Core/DayflowWindowsSyncSession.cs"

echo "Dayflow native client contracts are consistent."
